### PR TITLE
Simple ASCII to PETSCII conversion for C64 target

### PR DESCRIPTION
**Pull request by Claus64**
Adding a conversion from ASCII to PETSCII for C64 support.

### CODE REVIEW

**Comment by puppeh** [comment]
Thanks for the patch! Thinking about this a bit more though, I'm concerned it'll have unintended side-effects. For instance character literals won't be translated, so code which does something like:

```
int search(char* str, char c)
{
  int i = 0;
  for (; str[i]; i++)
  {
    if (str[i] == c)
      return i;
  }
  return -1;
}

... search("Hello", 'e') ...
```

may no longer do the intended thing if called with a string literal. So perhaps the correct thing to do is keep the internal character representation as ASCII, and convert to PETSCII in the putchar routine? Or alternatively, investigate further what the -fexec-charset option does.

**Comment by Claus64** [comment]
Good point! Hm, I do not really like having the data in a non-native format in the compiled program, as this seems rather inefficient to me. But I will dig a bit deeper into the conversion routines, possibly a patch that includes single character values might solve it. 

 

Von: puppeh [mailto:notifications@github.com] 
Gesendet: Montag, 16. Mai 2016 11:27
An: puppeh/gcc-6502 <gcc-6502@noreply.github.com>
Cc: Claus64 <claus_spenger@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [puppeh/gcc-6502] Simple ASCII to PETSCII conversion for C64 target (#5)

 

Thanks for the patch! Thinking about this a bit more though, I'm concerned it'll have unintended side-effects. For instance character literals won't be translated, so code which does something like:

int search(char* str, char c)
{
  int i = 0;
  for (; str[i]; i++)
  {
    if (str[i] == c)
      return i;
  }
  return -1;
}
 
... search("Hello", 'e') ...

may no longer do the intended thing if called with a string literal. So perhaps the correct thing to do is keep the internal character representation as ASCII, and convert to PETSCII in the putchar routine? Or alternatively, investigate further what the -fexec-charset option does.

**Comment by puppeh** [comment]
Maybe this converter can be adapted into a "custom converter" in libcpp/charset.c:init_iconv_desc()?

**Comment by Claus64** [comment]
I have a custom conversion in place now, that seems to do the right thing when  -fexec-charset=petscii is passed to gcc. I still need to figure out how to do this automatically for -mmach="c64" though.

**Comment by Claus64** [comment]
Hm, maybe not yet the best solution. Currently you cannot include characters > 127 in strings (e.g. "\x93", which would represent a clear screen). This would certainly be useful, but results in a range error, as it is converted to a ".byte $ffffff93" somewhere. I need to investigate a bit further :-).

**Comment by puppeh** [comment]
I've merged the work so far and added a small patch to enable the PETSCII exec charset by default with -mmach=c64. You can still override it with -fexec-charset=ascii if necessary.

**Comment by Claus64** [comment]
Perfect, thanks a lot! I will close this pull request and when I come up with a solution to the out of range error create a new one.

**Pull request closed without merging**
